language : node_js
node_js :
  - stable
install:
  - npm install
script:
  - npm run lint
  - npm run test
# Send coverage data to Coveralls
after_script: "jest --coverage && coveralls < coverage/lcov.info"
