language : node_js
node_js :
  - stable
install:
  - npm install
script:
  - npm run lint
  - npm run test
# Send coverage data to Coveralls
after_script: "nyc npm test && nyc report --reporter=text-lcov | coveralls"
